export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const LOAD_SHIPMENTS_SUCCESS = 'LOAD_SHIPMENTS_SUCCESS';
export const CREATE_SHIPMENT_SUCCESS = 'CREATE_SHIPMENT_SUCCESS';